Обрабатываем команды, которые вводит пользователь
htmlacademy-nodejs/497903-keksobooking pull request #2
Opened 2018-09-26 11:29 UTC by titov-andrei

2018-09-26 12:46 UTC, kicumkicum requested changes

2018-09-26 12:46 UTC, kicumkicum commented on index.js
> +if (process.argv = `--version`) {
напи-и, в 4ем разница между операторами `=`, `==` и `===`

2018-09-26 12:46 UTC, kicumkicum commented on index.js
> +if (process.argv = `--help`) {
какие данные должны лежать в `process.argv`? Какие ты ожидае-ь, а какие [на самом деле](https://nodejs.org/api/process.html#process_process_argv)?

2018-09-26 12:46 UTC, kicumkicum commented on index.js
> +  console.error(0);
4то должна сделать эта команда?

2018-09-26 15:53 UTC, titov-andrei commented on index.js
> +if (process.argv = `--version`) {
= присваивание, == сравнение, === строгое сравнение, учитывая типы - это я затупил конечно

2018-09-26 15:55 UTC, titov-andrei commented on index.js
> +if (process.argv = `--help`) {
поменял на process.argv[2] - так как возвращается массив и наш параметр будет третьим

2018-09-26 15:56 UTC, titov-andrei commented on index.js
> +  console.error(0);
по задумке - сработать по умолчанию - то есть при вызове без передачи параметров

2018-09-26 16:16 UTC, kicumkicum commented on index.js
> +  console.error(0);
покажи, как ты запускае-ь программу

2018-09-26 16:19 UTC, kicumkicum commented on index.js
> +  console.error(0);
а 4то произойдет то?)

Вот выполнили мы `console.error(0)` и как это повлияло на программу?
Для 4его эта строка здесь?

2018-09-26 16:57 UTC, titov-andrei commented on index.js
> +  console.error(0);
то есть если возвращает 0 - то выводить не нужно? и можно убрать строки с кодом возврата 0 - так?

2018-09-26 19:33 UTC, kicumkicum commented on index.js
> +  console.error(0);
По4ему ты отве4ае-ь вопросом на вопрос? 
Я же не просил ни4его изменять, а попросил об:яснить за4ем нужен этот код)
Об:яснять - это важно и полезно. Помогает лу4-е понять, 4то ты делае-ь, как и за4ем.
Есть даже [психологи4еский паттерн](https://experimental-psychic.ru/metod-utenka-dlya-resheniya-problem/) на эту тему.

Не бойся отве4ать на вопросы. Не бойся отве4ать на вопросы не правильно.
О-ибаться нормально, особенно на у4ебе.

К тому же отве4ать на вопросы быстрее, 4ем писать код. 
Поэтому прежде 4ем писать, стоит выяснить 4то не так, и как должно быть.
А потом уже писать)

2018-09-26 19:36 UTC, kicumkicum commented on index.js
> +  console.error(0);
На сколько я понял, ты с4итал, 4то в лйубом слу4ае нужно выводить код возврата.
Если это так, то да. `0` выводить в консоль не нужно.
Более того. Лйубой другой код возврата тоже не нужно выводить.
Нужно выводить информативное сооб=ение. А код возврата передавать в `process.exit`

2018-09-26 19:48 UTC, titov-andrei commented on index.js
> +  console.error(0);
Переписывал пока ответа ждал - комитил, чтобы процесс был выден - вопросы уточняющие, как раз для лучшего понимания - думаю через пару уроков будем лучше понимать о чём идёт речь

2018-09-26 19:57 UTC, kicumkicum commented on index.js
> +  console.error(0);
я не понял, по4ему ты удалил `process.exit(0)`. Не то, 4то бы это было плохо, но я не понял по4ему это произо-ло

2018-09-26 19:59 UTC, kicumkicum commented on index.js
> +      Автор: Кекс.
по условийу зада4и автор должен быть ты

2018-09-26 19:59 UTC, kicumkicum commented on index.js
> +      --version— печатает версию приложения;
тут и вы-е нужен пробел между version и тире

2018-09-27 08:54 UTC, kicumkicum approved these changes

2018-09-27 08:54 UTC, merged