создадим и настроим наш проект
htmlacademy-nodejs/497903-keksobooking pull request #3
Opened 2018-09-28 08:42 UTC by titov-andrei

2018-09-28 08:55 UTC, kicumkicum commented
test comment

2018-09-28 15:15 UTC, kicumkicum requested changes

2018-09-28 15:15 UTC, kicumkicum commented on package.json
> +    "eslint": "^5.6.0",
тут нару-ен критерий Б21. Но важный момент. Руками это править нельзя, только с помо=ьйу `npm`

2018-09-28 16:52 UTC, titov-andrei commented on package.json
> +    "eslint": "^5.6.0",
то есть нужно при установке пакета указать какой то параметр?

2018-09-28 18:41 UTC, kicumkicum commented on package.json
> +    "eslint": "^5.6.0",
совер-енно верно0

2018-09-29 09:53 UTC, titov-andrei commented on package.json
> +    "eslint": "^5.6.0",
https://htmlacademy.ru/blog/88-useful-commands-for-working-with-nodejs
"Если вы хотите установить конкретную версию пакета, воспользуйтесь префиксом @ с номером версии. Например, npm install package@1.0.1."
Как можно узнать, какую версию нужно устанавливать? В задании она ведь не указана?

2018-09-29 16:50 UTC, titov-andrei commented on package.json
> +    "eslint": "^5.6.0",
Через параметр @latest?

2018-09-30 13:17 UTC, kicumkicum commented on package.json
> +    "eslint": "^5.6.0",
нет. Параметр `latest` не фиксирует версийу. В слаке я скинул статьйу, которая расскажет тебе, как это можно сделать.

2018-09-30 13:19 UTC, kicumkicum approved these changes

2018-09-30 13:19 UTC, merged